from typing import Any, Protocol


class ParamStyleProtocol(Protocol):
    def add_param(self, value: int | str | float | None) -> tuple[str, str]:
        """
        Returns param key and placeholder
        """

    def get_parameters(self) -> dict[str, Any]: ...

    def get_list_parameters(self) -> list: ...

    def get_tuple_parameters(self) -> tuple: ...

    def reset_parameters(self): ...

    def was_param_added(self, key: str) -> bool: ...

    def get_param_by_key(self, key: str) -> int | str | float | None: ...


class DialectProtocol(Protocol):
    def quote_ident(self, name: str) -> str: ...

    def get_paramstyle(self) -> ParamStyleProtocol: ...
